#!/usr/bin/env python

import sys
from random import randint

print '''
Welcome to Guess the Number!
This game is kina shit but it's just for practice, K?

You have 5 tries to guess the number chosen by your computer between 0 and 100.
'''

MAX_ATTEMPTS = 5

_number = randint(0, 100)
_playing = True
_attempt = 1


def get_attempts_left():
	return MAX_ATTEMPTS - _attempt


# Game Loop:
while _playing:
	position = get_attempts_left()
	
	if position < 0:
		# We've lost the game:
		print "Sorry, dude, but you lost. Better luck next time."
		print "The number you wanted was %d" % _number
		_playing = False # This will break our loop.
	else:
		guess = int(input("Make a guess: "))
		
		# TODO: How can we protect ourselves from malicious input?
		
		if guess == _number:
			print "\nHooray!! You guessed the right number. You win!"
			_playing = False
		else:
			if guess < _number:
				print "Too low, bro."
			elif guess > _number:
				print "Too high, guy."
			print "You have %d guesses left.\n" % position
			_attempt += 1

print "\nThanks for playing!! =)\n"